import pandas as pd
import numpy as np

class PnLEngine:
    """
    Computes daily PnL timeseries for:
        - unhedged portfolio
        - hedge instruments
        - hedged portfolio

    PnL Formula:
        PnL_t = -sum_{k}(DV01_{t-1} * dy_{t})

        where:
            k: key_rate tenor
            DV01: dlooar value of 1 bp
            dy: daily yield change

    Net Hedged PnL Formula:
        PnL_net = PnL_portfolio + PnL_hedge
    """

    # unhedged portfolio PnL
    @staticmethod
    def compute_unhedged_pnl(
            portfolio,
            df_curve,
            key_rate_tenors
    ):
        """ Computing unhedged daily portfolio PnL timeseries """
        # portfolio DV01 timeseries
        portfolio_dv01 = portfolio.portfolio_dv01(
            df_curve = df_curve,
            shock_type = 'key_rate',
            key_rate_tenors = key_rate_tenors
        )

        # align column names with key-rate tenors
        portfolio_dv01.columns = key_rate_tenors

        # extract key-rate yields
        key_rate_yields = df_curve[key_rate_tenors]

        # daily yield changes dy -> convert decimal points into bps
        dy = key_rate_yields.diff().fillna(0) * 10000

        # align DV01 (use DV01_{t-1} for dy_{t} move)
        portfolio_dv01_lag = portfolio_dv01.shift(1).fillna(0)

        # daily PnL using DV01 proxy
        daily_pnl = -(portfolio_dv01_lag * dy).sum(axis = 1)

        # cumulative PnL
        cumulative_pnl = daily_pnl.cumsum()

        return cumulative_pnl
    
    # hedge PnL
    @staticmethod
    def compute_hedge_pnl(
        rolling_hedge_engine,
        hedge_universe,
        df_curve,
        key_rate_tenors
    ):
        """ Computing historical PnL generated by hedge trades only """
        # DV01 of hedge portfolio timeseries
        hedge_dv01 = rolling_hedge_engine._build_daily_hedge_dv01(
            hedge_universe = hedge_universe,
            df_curve = df_curve,
            hedge_positions = rolling_hedge_engine.hedge_positions,
            key_rate_tenors = key_rate_tenors
        )

        # daily yield changes dy in bps
        dy = rolling_hedge_engine._compute_yield_changes(yield_curve = df_curve) * 10000

        # align DV01
        hedge_dv01 = hedge_dv01.loc[dy.index]

        hedge_dv01_lag = hedge_dv01.shift(1).fillna(0)

        # hedge PnL using DV01 proxy
        daily_hedge_pnl = +(hedge_dv01_lag * dy).sum(axis=1)

        # cumulative hedge PnL
        cumulative_hedge_pnl = daily_hedge_pnl.cumsum()

        return cumulative_hedge_pnl
    

    # hedged PnL
    def compute_hedged_strategy_pnl(
            self,
            rolling_hedge_engine,
            portfolio,
            hedge_universe,
            df_curve,
            key_rate_tenors
    ):
        """ Full hedged strategy PnL """
        # computing unhedged PnL 
        unhedged = self.compute_unhedged_pnl(
            portfolio = portfolio,
            df_curve = df_curve,
            key_rate_tenors = key_rate_tenors
        )

        # computing hedge PnL 
        hedge = self.compute_hedge_pnl(
            rolling_hedge_engine = rolling_hedge_engine,
            hedge_universe = hedge_universe,
            df_curve = df_curve,
            key_rate_tenors = key_rate_tenors
        )

        # total PnL
        hedged = unhedged + hedge

        return hedged
    